# Site settings
title: "Ari's blog on learning Chinese, and studying law"
author: "Ari Wigdorowitz"
description: "I built this website in June 2019 using Jekyll and the 'papyrus' theme which can be found on github. Here you can find essays on law and philosophy. These essays were predominantly written during my time as an undergraduate student at Monash University. I also publish stories about my experiences learning Chinese (Mandarin) as well as the odd translation."
keywords: "Philosophy, Law, Chinese, Language"
biography: "My name is Ari and I am a law student at Monash University in Melbourne Australia. I learn Chinese (Mandarin) in my spare time and occassionaly dabble in rudimentary front-end web development."
colophon: "© 2019"

baseurl: "/papyrus"
url: "http://hugosereno.eu"

twitter_username: Wigda
google-analytics: UA-141809411-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
