# Site settings
title: "Ari's blog on whatever comes to mind"
author: "Ari Wigdorowitz"
description: "I built this website in June 2019 using Jekyll 'Papyrus' which can be found on github. Here you can find some of my ramblings. "
keywords: "Philosophy, Law, Chinese, Language"
biography: "My name is Ari and I am a law student at Monash University in Melbourne Australia. I learn Chinese (Mandarin) in my spare time."
colophon: "© 2019"

baseurl: "/papyrus"
url: "http://hugosereno.eu"

twitter_username: Wigda
google-analytics: UA-141809411-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
