# Site settings
title: "Ari's blog on Australian law and on Mandarin Chinese."
author: "Ari Wigdorowitz"
description: "I built this website in June 2019. Here you can find essays that I have written during my undergraduate years at Monash University. I also publish stories about my experiences learning Chinese."
keywords: "Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a law student at Monash University in Melbourne Australia and an avid Chinese language learner."
colophon: "© 2019 my thanks goes to github for gratuitously hosting this webpage <a href='https://pages.github.com/'>Github Pages</a> thanks also goes to <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: "/papyrus"
url: "http://hugosereno.eu"

twitter_username: Wigda
google-analytics: UA-141809411-1

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
