# Site settings
title: "On Australian law, Chinese language studies and philosophy "
author: "Ari Wigdorowitz"
description: "This is a blog about Australian Law, Chinese language studies , and the occasional philosophy. Not necessarily in that order."
keywords: "Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a law student at Monash University in Melbourne Australia and an avid Chinese language learner."
colophon: "© MMXIII — MMXVI This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: "/papyrus"
url: "http://hugosereno.eu"

twitter_username: Wigdo
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
